In [2]:
import numpy as np
import pandas as pd
import random

Wskaźnik uwarunkowania macierzy

In [69]:
def norm(A):
    n = len(A)
    return max(sum(A[i][j] for j in range(n)) for i in range(n))

In [70]:
def conditioning_factor(A):
    A_inv = np.linalg.inv(A)
    return norm(A_inv) * norm(A)

Gaussian Elimination

![title](img_vsc/img01.png)

![title](img_vsc/img02.png)

In [49]:
def gaussian_elimination(A, B, data_type):
    
    n = A.shape[0]
    
    C = np.hstack((A, B.reshape(n, 1)))

    for i in range(n):
        for j in range(i + 1, n):
            ratio = C[j][i] / C[i][i]
            C[j] = C[j] - ratio * C[i]

    X = np.zeros(n, dtype=data_type)

    X[n - 1] = C[n - 1][n] / C[n - 1][n - 1] # We now have n + 1 columns

    for i  in range(n - 2 , -1, -1):
        X[i] = (C[i][n] - sum(X[i+1:n]*C[i][i+1:n])) / C[i][i]
        
    return X

In [85]:
class GaussTest():
    
    def __init__(self, get_matrix_function):

        self.get_matrix = get_matrix_function

    def random_vector(self, n):
        
        random.seed(555)
        
        V = []
        
        for _ in range(n):
            V.append( -1 if random.random() < 0.5 else 1)
            
        return V
        
    def solve(self, n, data_type):
        
        A = self.get_matrix(n)   
        X = self.random_vector(n)
        
        A = np.array(A, dtype=data_type).reshape(n, n)
        X = np.array(X, dtype=data_type).reshape(n)
        
        B = A @ X
        
        X_approx = gaussian_elimination(A, B, data_type)
        
        if data_type == np.float32 or data_type == np.float64:
            return X, X_approx, conditioning_factor(A)
        else:
            return X, X_approx, None

In [86]:
def zad1_matrix(n):
    
    A = []
        
    for i in range(1, n + 1):
        for j in range(1, n + 1):
                
            if i == 1:
                A.append(1)
            else:
                A.append(1 / (i + j - 1)) 
                    
    return A

In [87]:
zad1 = GaussTest(zad1_matrix)

X, X_approx, cf = zad1.solve(5, np.float16)
print(X, X_approx, cf)

[-1. -1.  1.  1. -1.] [-1.232  0.896 -3.867  6.01  -2.809] None


In [88]:
zad1 = GaussTest(zad1_matrix)

X, X_approx, cf = zad1.solve(5, np.float32)
print(X, X_approx, cf)

[-1. -1.  1.  1. -1.] [-0.9998863 -1.0011003  1.0032243  0.9963035 -0.9985412] 28023.636474609375


In [89]:
zad1 = GaussTest(zad1_matrix)

X, X_approx, cf = zad1.solve(5, np.float64)
print(X, X_approx, cf)

[-1. -1.  1.  1. -1.] [-1. -1.  1.  1. -1.] 28000.000000047658


In [7]:
def zad2_matrix(n):
    
    A = [[0 for j in range(1, n + 1)] for i in range(1, n + 1)]
    
    for i in range(1, n + 1):
        for j in range(1, n + 1):
            
            if j >= i:
                A[i - 1][j - 1] = 2 * i / j
            else:
                A[i - 1][j - 1] = A[j - 1][i - 1]
                
    return A

In [90]:
zad2 = GaussTest(zad2_matrix)

X, X_approx, cf = zad2.solve(5, np.float16)
print(X, X_approx, cf)

[-1. -1.  1.  1. -1.] [-1.    -1.     1.     1.001 -1.001] None


In [91]:
zad2 = GaussTest(zad2_matrix)

X, X_approx, cf = zad2.solve(5, np.float32)
print(X, X_approx, cf)

[-1. -1.  1.  1. -1.] [-1.0000001 -0.9999997  0.9999998  1.        -1.       ] 2.233333435654641


In [92]:
zad2 = GaussTest(zad2_matrix)

X, X_approx, cf = zad2.solve(5, np.float64)
print(X, X_approx, cf)

[-1. -1.  1.  1. -1.] [-1. -1.  1.  1. -1.] 2.233333333333334


In [11]:
def zad3a_matrix(n):

    k = 6
    m = 3

    A = [[0 for j in range(1, n + 1)] for i in range(1, n + 1)]

    for i in range(1, n + 1):
        for j in range(1, n + 1):

            if j == i:
                A[i - 1][j - 1] = k
            elif j == i + 1:
                A[i - 1][j - 1] = 1 / (i + m)
            elif i > 1 and j == i - 1:
                A[i - 1][j - 1] = k / (i + m + 1)

    return A

In [93]:
zad3a = GaussTest(zad3a_matrix)

X, X_approx, cf = zad3a.solve(5, np.float16)
print(X, X_approx, cf)

[-1. -1.  1.  1. -1.] [-1.     -1.      0.9995  0.9995 -1.    ] None


In [94]:
zad3a = GaussTest(zad3a_matrix)

X, X_approx, cf = zad3a.solve(5, np.float32)
print(X, X_approx, cf)

[-1. -1.  1.  1. -1.] [-1.         -0.99999994  1.          1.         -1.0000001 ] 1.159485363403662


In [95]:
zad3a = GaussTest(zad3a_matrix)

X, X_approx, cf = zad3a.solve(5, np.float64)
print(X, X_approx, cf)

[-1. -1.  1.  1. -1.] [-1. -1.  1.  1. -1.] 1.1594853983864615


In [23]:
def zad3b_matrix(n):

    k = 6
    m = 3

    A = [[0 for j in range(1, n + 1)] for i in range(1, n + 1)]

    for i in range(1, n + 1):
        for j in range(1, n + 1):
            
            if j == i:
                A[i - 1][j - 1] = -m * i - k
            elif j == i + 1:
                A[i - 1][j - 1] = i
            elif i > 1 and j == i - 1:
                A[i - 1][j - 1] = m / i

    return A

In [96]:
zad3b = GaussTest(zad3b_matrix)

X, X_approx, cf = zad3b.solve(5, np.float16)
print(X, X_approx, cf)

[-1. -1.  1.  1. -1.] [-1. -1.  1.  1. -1.] None


In [97]:
zad3b = GaussTest(zad3b_matrix)

X, X_approx, cf= zad3b.solve(5, np.float32)
print(X, X_approx, cf)

[-1. -1.  1.  1. -1.] [-1. -1.  1.  1. -1.] 0.3970123413610054


In [98]:
zad3b = GaussTest(zad3b_matrix)

X, X_approx, cf = zad3b.solve(5, np.float64)
print(X, X_approx, cf)

[-1. -1.  1.  1. -1.] [-1. -1.  1.  1. -1.] 0.3970123323338485


Algorytm Thomasa dla macierzy trójdiagonalnej

In [99]:
def thomas_algorithm(A, B, C, D):
    
    N = len(B)
    
    C[0] /= B[0]
    D[0] /= B[0]
    
    for i in range(1, N - 1):
        
        common_coefficient = B[i] - A[i - 1] * C[i - 1]
        
        C[i] /= common_coefficient
        D[i] = (D[i] - A[i - 1] * D[i - 1])  / common_coefficient
        
    # Since loop goes only to n - 1, we need to calculate the last element of D
    D[N - 1] = (D[N - 1] - A[N - 2] * D[N - 2]) / (B[N - 1] - A[N - 2] * C[N - 2])
    
    # Backward substitution
    X = [0] * N
    X[-1] = D[-1]
    
    for i in range(N - 2, -1, -1):
        X[i] = D[i] - C[i] * X[i + 1]
        
    return X    

In [100]:
A = [3, 1, 3]
B = [10, 10, 7, 4]
C = [2, 4, 5]
D = [3, 4, 5, 6]

X = thomas_algorithm(A, B, C, D)
print(X)


A = np.array([[10,2,0,0],[3,10,4,0],[0,1,7,5],[0,0,3,4]],dtype=float)   
a = np.array([3.,1,3]) 
b = np.array([10.,10.,7.,4.])
c = np.array([2.,4.,5.])
d = np.array([3,4,5,6.])
print(np.linalg.solve(A, d))

[0.14877589453860635, 0.7561205273069682, -1.0018832391713752, 2.2514124293785316]
[ 0.14877589  0.75612053 -1.00188324  2.25141243]
